networks:
    frontend_network:
        name: frontend_network
        driver: bridge
    backend_network:
        name: backend_network
        driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.19
    deploy:
        resources:
            limits:
                cpus: '0.15'
                memory: 64M
    volumes:
        - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
        - backend_network
    healthcheck:
        test: 'pg_isready -U ${POSTGRES_USER}'
        interval: 5s
        timeout: 3s
        retries: 5
  redis_cache:
    container_name: redis_cache
    image: redis:7.2.4-alpine
    deploy:
        resources:
            limits:
                cpus: '0.1'
                memory: 96M
    restart: always
    environment:
        REDIS_PORT: ${REDIS_CACHE_PORT}
        REDIS_DATABASES: ${REDIS_CACHE_DATABASES}
    command: redis-server --save 60 10
    networks:
        - backend_network
  backend:
    container_name: backend_takejoboffer
    build:
        context: .
        dockerfile: /TakeJobOffer.API/API.Dockerfile
    deploy:
        resources:
            limits:
                cpus: '0.25'
                memory: 256M
    restart: always
    environment:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        ASPNETCORE_HTTPS_PORTS: ${ASPNETCORE_HTTPS_PORTS}
        ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
        ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_Kestrel__Certificates__Default__Password}
        ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_Kestrel__Certificates__Default__Path}
    networks:
        - frontend_network
        - backend_network
    volumes:
        - ~/.aspnet/https:/home/app/.aspnet/https:ro
    depends_on:
        postgres:
            condition: service_healthy
            restart: true
        redis_cache:
            condition: service_started
            restart: true
    healthcheck:
        test: curl --fail http://localhost:${ASPNETCORE_HTTP_PORTS}/health || exit 1
        interval: 6s
        timeout: 3s
        retries: 5
        start_period: 3s
  frontend:
    container_name: frontend_takejoboffer
    build:
        context: ./Frontend/takejobofferfrontend
        dockerfile: Frontend.Dockerfile
    restart: always
    deploy:
        resources:
            limits:
                cpus: '0.2'
                memory: 128M
    networks:
        - frontend_network
    depends_on:
        backend:
            condition: service_healthy
            restart: true
  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    restart: always
    deploy:
        resources:
            limits:
                cpus: '0.1'
                memory: 32M
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./ReverseProxy/static:/static
        - ./ReverseProxy/nginx/Production:/etc/nginx/conf.d/
        - www-html:/var/www/html/:ro
        - ssl-crt:/etc/nginx/ssl/:ro
    depends_on:
        backend:
            condition: service_healthy
            restart: true
        frontend:
            condition: service_started
            restart: true
    networks:
        - frontend_network
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    deploy:
        resources:
            limits:
                cpus: '0.05'
                memory: 16M
    depends_on:
        - nginx
    volumes:
        - www-html:/var/www/html/:rw
        - ssl-crt:/etc/sslcert/:rw
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --staging -d takejoboffer.ru
volumes:
    postgres-data:
    ssl-crt:
    www-html: