version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_DB: "takejobofferdb"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "123"
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
volumes:
    postgres-data:
